export interface WordEntry {
  word: string;
  category: string;
}

const WORD_LIST: WordEntry[] = [
  // Animals (25) — Extremely well-known animals with famous synonyms & traits
  { word: "Bat", category: "Animals" },
  { word: "Kangaroo", category: "Animals" },
  { word: "Lion", category: "Animals" },
  { word: "Bear", category: "Animals" },
  { word: "Monkey", category: "Animals" },
  { word: "Elephant", category: "Animals" },
  { word: "Tiger", category: "Animals" },
  { word: "Rabbit", category: "Animals" },
  { word: "Horse", category: "Animals" },
  { word: "Snake", category: "Animals" },
  { word: "Bird", category: "Animals" },
  { word: "Frog", category: "Animals" },
  { word: "Pig", category: "Animals" },
  { word: "Cow", category: "Animals" },
  { word: "Sheep", category: "Animals" },
  { word: "Duck", category: "Animals" },
  { word: "Shark", category: "Animals" },
  { word: "Eagle", category: "Animals" },
  { word: "Fox", category: "Animals" },
  { word: "Mouse", category: "Animals" },
  { word: "Wolf", category: "Animals" },
  { word: "Owl", category: "Animals" },
  { word: "Whale", category: "Animals" },
  { word: "Spider", category: "Animals" },
  { word: "Giraffe", category: "Animals" },

  // Food & Drink (25) — Popular everyday foods with clear descriptors
  { word: "Pizza", category: "Food" },
  { word: "Burger", category: "Food" },
  { word: "Coffee", category: "Food" },
  { word: "Tea", category: "Food" },
  { word: "Ice Cream", category: "Food" },
  { word: "Cake", category: "Food" },
  { word: "Chocolate", category: "Food" },
  { word: "Apple", category: "Food" },
  { word: "Bread", category: "Food" },
  { word: "Cheese", category: "Food" },
  { word: "Soup", category: "Food" },
  { word: "Taco", category: "Food" },
  { word: "Pancake", category: "Food" },
  { word: "Donut", category: "Food" },
  { word: "Salad", category: "Food" },
  { word: "Pasta", category: "Food" },
  { word: "Cookie", category: "Food" },
  { word: "Milk", category: "Food" },
  { word: "Sandwich", category: "Food" },
  { word: "Potato", category: "Food" },
  { word: "Rice", category: "Food" },
  { word: "Steak", category: "Food" },
  { word: "Juice", category: "Food" },
  { word: "Egg", category: "Food" },
  { word: "Banana", category: "Food" },

  // Nature & Elements (25) — Universal nature concepts
  { word: "Sun", category: "Nature" },
  { word: "Moon", category: "Nature" },
  { word: "Ocean", category: "Nature" },
  { word: "River", category: "Nature" },
  { word: "Mountain", category: "Nature" },
  { word: "Rain", category: "Nature" },
  { word: "Snow", category: "Nature" },
  { word: "Fire", category: "Nature" },
  { word: "Wind", category: "Nature" },
  { word: "Forest", category: "Nature" },
  { word: "Beach", category: "Nature" },
  { word: "Cloud", category: "Nature" },
  { word: "Star", category: "Nature" },
  { word: "Thunder", category: "Nature" },
  { word: "Lightning", category: "Nature" },
  { word: "Volcano", category: "Nature" },
  { word: "Waterfall", category: "Nature" },
  { word: "Island", category: "Nature" },
  { word: "Desert", category: "Nature" },
  { word: "Cave", category: "Nature" },
  { word: "Flower", category: "Nature" },
  { word: "Tree", category: "Nature" },
  { word: "Lake", category: "Nature" },
  { word: "Sky", category: "Nature" },
  { word: "Rainbow", category: "Nature" },

  // Everyday Objects (25) — Common household items
  { word: "Phone", category: "Everyday Objects" },
  { word: "Clock", category: "Everyday Objects" },
  { word: "Mirror", category: "Everyday Objects" },
  { word: "Camera", category: "Everyday Objects" },
  { word: "Key", category: "Everyday Objects" },
  { word: "Book", category: "Everyday Objects" },
  { word: "Chair", category: "Everyday Objects" },
  { word: "Bed", category: "Everyday Objects" },
  { word: "Shoe", category: "Everyday Objects" },
  { word: "Car", category: "Everyday Objects" },
  { word: "Door", category: "Everyday Objects" },
  { word: "Lamp", category: "Everyday Objects" },
  { word: "Bottle", category: "Everyday Objects" },
  { word: "Glasses", category: "Everyday Objects" },
  { word: "Umbrella", category: "Everyday Objects" },
  { word: "Wallet", category: "Everyday Objects" },
  { word: "Headphones", category: "Everyday Objects" },
  { word: "Keyboard", category: "Everyday Objects" },
  { word: "Candle", category: "Everyday Objects" },
  { word: "Blanket", category: "Everyday Objects" },
  { word: "Scissors", category: "Everyday Objects" },
  { word: "Guitar", category: "Everyday Objects" },
  { word: "Watch", category: "Everyday Objects" },
  { word: "Computer", category: "Everyday Objects" },
  { word: "Pillow", category: "Everyday Objects" },

  // Places & Destinations (25) — Universally recognizable locations
  { word: "Airport", category: "Places" },
  { word: "School", category: "Places" },
  { word: "Hospital", category: "Places" },
  { word: "Park", category: "Places" },
  { word: "Cinema", category: "Places" },
  { word: "Library", category: "Places" },
  { word: "Hotel", category: "Places" },
  { word: "Restaurant", category: "Places" },
  { word: "Castle", category: "Places" },
  { word: "Bank", category: "Places" },
  { word: "Bakery", category: "Places" },
  { word: "Stadium", category: "Places" },
  { word: "Museum", category: "Places" },
  { word: "Market", category: "Places" },
  { word: "Zoo", category: "Places" },
  { word: "Farm", category: "Places" },
  { word: "Station", category: "Places" },
  { word: "Gym", category: "Places" },
  { word: "Kitchen", category: "Places" },
  { word: "Office", category: "Places" },
  { word: "Store", category: "Places" },
  { word: "Aquarium", category: "Places" },
  { word: "Playground", category: "Places" },
  { word: "Submarine", category: "Places" },
  { word: "Spaceship", category: "Places" },

  // Professions & Roles (25) — Famous jobs & roles with rich clues
  { word: "Doctor", category: "Professions & Roles" },
  { word: "Teacher", category: "Professions & Roles" },
  { word: "Pilot", category: "Professions & Roles" },
  { word: "Chef", category: "Professions & Roles" },
  { word: "Police", category: "Professions & Roles" },
  { word: "Firefighter", category: "Professions & Roles" },
  { word: "Singer", category: "Professions & Roles" },
  { word: "Actor", category: "Professions & Roles" },
  { word: "Farmer", category: "Professions & Roles" },
  { word: "Driver", category: "Professions & Roles" },
  { word: "King", category: "Professions & Roles" },
  { word: "Queen", category: "Professions & Roles" },
  { word: "Judge", category: "Professions & Roles" },
  { word: "Soldier", category: "Professions & Roles" },
  { word: "Pirate", category: "Professions & Roles" },
  { word: "Detective", category: "Professions & Roles" },
  { word: "Astronaut", category: "Professions & Roles" },
  { word: "Magician", category: "Professions & Roles" },
  { word: "Ninja", category: "Professions & Roles" },
  { word: "Hero", category: "Professions & Roles" },
  { word: "Artist", category: "Professions & Roles" },
  { word: "Writer", category: "Professions & Roles" },
  { word: "Nurse", category: "Professions & Roles" },
  { word: "Guard", category: "Professions & Roles" },
  { word: "Sailor", category: "Professions & Roles" },
];

/**
 * Returns a random word entry from the full word list.
 */
export function getRandomWord(): WordEntry {
  const index = Math.floor(Math.random() * WORD_LIST.length);
  return WORD_LIST[index];
}

/** Returns all available categories. */
export function getCategories(): string[] {
  return [...new Set(WORD_LIST.map((w) => w.category))];
}

export { WORD_LIST };
